export const tips = [
    {
        key: 'invoice-add',
        title: '我们会根据您填写的信息来邮寄发票',
        icon: 'wenhao1',
        placement: 'right',
        show: true,
    },
    {
        key: 'product-finished',
        title: '下架后，商品将不再展现在手机端商城货架',
        show: true,
    },
    {
        key: 'product-opening',
        title: '上架后，商品将展现在手机端商城货架上',
        show: true,
    },
    {
        key: 'product-info',
        title: '该修改不影响商城中商品详情',
        show: true,
    },
    {
        key: 'product-basic',
        title: '已上架商品，先下架,然后修改商品交易设置',
        show: true,
    },
    {
        key: 'product-delete',
        title: '从未上架过的商品，可以删除，删除后该商品会彻底从商品库移除',
        show: true,
    },
    {
        key: 'product-add',
        title: '复制后，生成一件全新的商品，方便您添加类似商品',
        show: true,
    },
    {
        key: 'yyg-opening',
        title: '上架后，商品将展现在手机端一元购货架',
        show: true,
    },
    {
        key: 'yyg-finished',
        title: '暂停该商品的一元购活动，当期尚未完成抽奖的商品将不受影响，继续一元购流程',
        show: true,
    },
    {
        key: 'yyg-continue-opening',
        title: '恢复该商品的一元购活动，当期完成抽奖流程后，下期将自动上架',
        show: true,
    },
    {
        key: 'yyg-info',
        title: '该修改不影响商城中商品详情',
        show: true,
    },
    {
        key: 'yyg-trade',
        title: '修改后的规则将在下一期开始生效，当期尚未完成抽奖的商品将不受影响',
        show: true,
    },
    {
        key: 'yyg-delete',
        title: '从一元购活动待定商品中移除，不影响商品库',
        show: true,
    },
    {
        key: 'profit-setting',
        title: '设置用来收款、付款的账号',
        icon: 'wenhao1',
        placement: 'right',
        show: true,
    },
    {
        key: 'charge-account',
        title: '显示剩余乐豆及过往的充值、消费明细',
        icon: 'wenhao1',
        placement: 'right',
        show: true,
    },
    {
        key: 'setting-trading',
        title: '如不设置或解除绑定,系统会自动启用默认配置信息,不会影响爆款商城交易',
        icon: 'wenhao1',
        placement: 'right',
        show: true,
    },
    {
        key: 'content-color',
        title: '主题色',
        placement: 'right',
        show: true,
    },
    {
        key: 'content-recolor',
        title: '重置主题色',
        placement: 'bottom',
        show: true,
    },
    {
        key: 'mould-package',
        title: '整套使用',
        placement: 'right',
        show: true,
    },
    {
        key: 'mould-partitioning',
        title: '分块使用',
        placement: 'left',
        show: true,
    },
    {

        key: 'content-release-immediately',
        icon: 'wenhao1',
        placement: 'top',
        title: '用户将立即收到该图文。',
        show: true,
    },
    {
        key: 'content-release-interval',
        icon: 'wenhao1',
        placement: 'top',
        title: '用户在公众号中回复任意消息，将立即收到该图文',
        show: true,
    },
    {
        key: 'content-release-send',
        icon: 'wenhao1',
        placement: 'top',
        title: '正式发布前，可先推送给运营人员预览',
        show: true,
    },
    {
        key: 'content-release-send',
        icon: 'wenhao1',
        placement: 'top',
        title: '正式发布前，可先推送给运营人员预览',
        show: true,
    },
    /*个人中心文案汇总*/
    {
        key: 'user-upgrade-1',
        icon: 'wenhao1',
        placement: 'right',
        title: '可免费试用编辑器的基本功能',
        show: true,
    },
    {
        key: 'user-upgrade-2',
        icon: 'wenhao1',
        placement: 'right',
        title: '支持更多营销插件，专属客服',
        show: true,
    },
    {
        key: 'user-upgrade-3',
        icon: 'wenhao1',
        placement: 'right',
        title: '免费使用创建、发布图文',
        show: true,
    },
    {
        key: 'user-upgrade-4',
        icon: 'wenhao1',
        placement: 'right',
        title: '丰富的导购、营销插件',
        show: true,
    },
    {
        key: 'user-upgrade-5',
        icon: 'wenhao1',
        placement: 'right',
        title: '每个账号可独立运营一个公司的业务，让您轻松玩转多个公司的运营业务',
        show: true,
    },
    {
        key: 'user-upgrade-6',
        icon: 'wenhao1',
        placement: 'right',
        title: '多个渠道的分发',
        show: true,
    },
    {
        key: 'user-upgrade-7',
        icon: 'wenhao1',
        placement: 'right',
        title: '全方位的数据统计，指导您如何提高阅读量/粉丝转化率',
        show: true,
    },
    {
        key: 'user-upgrade-8',
        icon: 'wenhao1',
        placement: 'right',
        title: '专业客服在线指导，即使是小白，也能快速上手',
        show: true,
    },
    {
        key: 'user-upgrade-9',
        icon: 'wenhao1',
        placement: 'right',
        title: '快速、精准地将内容推向目标客户',
        show: true,
    },
    {
        key: 'user-upgrade-10',
        icon: 'wenhao1',
        placement: 'right',
        title: '使用阿里云高端服务器，让您安枕无忧',
        show: true,
    },
    {
        key: 'user-upgrade-11',
        icon: 'wenhao1',
        placement: 'right',
        title: '限时免费使用H5编辑器',
        show: true,
    }, {
        key: 'user-upgrade-12',
        icon: 'wenhao1',
        placement: 'right',
        title: '场景化的导购、营销插件',
        show: true,
    },
    {
        key: 'user-upgrade-13',
        icon: 'wenhao1',
        placement: 'right',
        title: '指的是浏览图文的次数。如果是H5，则每浏览一次H5将抵扣10篇图文的次数。',
        show: true,
    },
    {
        key: 'user-upgrade-14',
        icon: 'wenhao1',
        placement: 'right',
        title: '指的是存储图文的篇数。如果是H5，则每存储一篇H5将占用10篇图文的存储篇数。',
        show: true,
    },
    {
        key: 'home-marketing-idea',
        icon: 'wenhao1',
        title: '我很乖，嘴甜的棉花糖都给你，最棒的营销建议也给你。(●\'◡\'●)ﾉ♥',
        show: true,
    }, {
        key: 'home-marketing-entrance',
        icon: 'wenhao1',
        title: '我就是个收藏夹啦 (♥ó㉨ò)ﾉ♡，在这里你可以添加自己的常用菜单。',
        show: true,
    }, {
        key: 'home-account-info',
        icon: 'wenhao1',
        title: '点我点我！看看你的账户信息，可能会有意想不到的发现！',
        show: true,
    }, {
        key: 'home-data-statistics',
        icon: 'wenhao1',
        title: '告诉你个小秘密~这可不是一般的数据概况。我主子的粉丝增长情况（所有授权账号总和）可以在这里看，主子东西卖得好不好也在这里看哦。',
        show: true,
    }

];
