// 产品功能Key - 详情请查看平台产品中心-产品配置-功能管理

export const CONTENT_RICHTEXT_CREATE = 'CONTENT_RICHTEXT_CREATE'; //制作图文
export const CONTENT_RICHTEXT_BUY = 'CONTENT_RICHTEXT_BUY'; //购买(素材/模板)
export const CONTENT_RICHTEXT_IMPORT = 'CONTENT_RICHTEXT_IMPORT'; //导入资讯
export const CONTENT_RICHTEXT_FAV = 'CONTENT_RICHTEXT_FAV'; //收藏（素材/模板/资讯）
export const CONTENT_RICHTEXT_UPLOAD = 'CONTENT_RICHTEXT_UPLOAD'; //上传图片保存到云端
export const CONTENT_RICHTEXT_DEL = 'CONTENT_RICHTEXT_DEL'; //下架已发布到微站的图文/删除未发布的图文
export const CONTENT_MESSAGE_CHECK = 'CONTENT_MESSAGE_CHECK'; //审核用户的留言
export const CONTENT_RICHTEXT_PUBLISH = 'CONTENT_RICHTEXT_PUBLISH'; //发布图文
export const CONTENT_RICHTEXT_SAVE = 'CONTENT_RICHTEXT_SAVE'; //保存/预览图文
export const CONTENT_MARKETING_GIFT = 'CONTENT_MARKETING_GIFT'; //使用红包插件
export const CONTENT_MARKETING_ACTIVITY = 'CONTENT_MARKETING_ACTIVITY'; //使用活动插件
export const CONTENT_MARKETING_SALE = 'CONTENT_MARKETING_SALE'; //使用导购插件
export const CONTENT_MARKETING_PRAISE = 'CONTENT_MARKETING_PRAISE'; //使用点赞插件
export const CONTENT_MARKETING_AWARD = 'CONTENT_MARKETING_AWARD'; //使用打赏插件
export const CONTENT_MARKETING_MESSAGE = 'CONTENT_MARKETING_MESSAGE'; //使用留言插件
export const CONTENT_RICHTEXT_STATISTICS = 'CONTENT_RICHTEXT_STATISTICS'; //查看图文的统计数据
export const MPLUGIN_COUPON_CREATE = 'MPLUGIN_COUPON_CREATE'; //管理优惠券和积分
export const PAYMENT_ACCOUNT_CHARGE = 'PAYMENT_ACCOUNT_CHARGE'; //账户充值及明细查看
export const PAYMENT_ACCOUNT_CONSUME = 'PAYMENT_ACCOUNT_CONSUME'; //查看乐豆的消费明细
export const PAYMENT_WITHDRAW_WITHDRAW = 'PAYMENT_WITHDRAW_WITHDRAW'; //收益提现
export const PAYMENT_SETTING_SETTING = 'PAYMENT_SETTING_SETTING'; //设置交易账户
export const PAYMENT_BILL_MANAGEMENT = 'PAYMENT_BILL_MANAGEMENT'; //发票管理
export const PLATFORM_MICSITE_MODULE = 'PLATFORM_MICSITE_MODULE'; //管理微站中的模块/布局等基本信息
export const PLATFORM_ACCESS_AUTHORITY = 'PLATFORM_ACCESS_AUTHORITY'; //发布渠道的授权
export const PLATFORM_ACCOUNT_CREATE = 'PLATFORM_ACCOUNT_CREATE'; //管理子账号
export const CONTENT_HFIVE_CREATE = 'CONTENT_HFIVE_CREATE'; //制作H5/查看发布记录
export const CONTENT_RICHTEXT_REPLY = 'CONTENT_RICHTEXT_REPLY'; //微信公众号中自动回复图文

export const CONTENT_H5_COUPON = 'CONTENT_H5_COUPON'; // h5编辑器优惠券插件
export const CONTENT_H5_ACTIVITY = 'CONTENT_H5_ACTIVITY'; // h5编辑器活动插件
export const CONTENT_H5_SALE = 'CONTENT_H5_SALE'; // h5编辑器导购插件
export const CONTENT_H5_SAVE = 'CONTENT_H5_SAVE'; // h5编辑器保存
export const CONTENT_H5_PUBLISH = 'CONTENT_H5_PUBLISH'; // h5编辑器发布

export const CONTENT_H5_CREATE = 'CONTENT_H5_CREATE';//新建活动H5
export const CONTENT_H5_FAV = 'CONTENT_H5_FAV';//收藏活动H5
export const CONTENT_H5_BUY = 'CONTENT_H5_BUY';//购买活动H5
export const CONTENT_H5_DEL = 'CONTENT_H5_DEL';//H5微站下架或者删除
export const CONTENT_H5_STATISTICS = 'CONTENT_H5_STATISTICS';//H5数据统计
